# 公共配置文件
# @author Treay
# 
spring:
  profiles:
    active: dev
  application:
    name: yujian-backend
  # DataSource Config
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://8.130.136.183:3306/yujian?serverTimezone=Asia/Shanghai
#    username: yujian
#    password: wMXPRATjPCnaYApR
    url: jdbc:mysql://localhost:3306/partnermatching?serverTimezone=Asia/Shanghai
    username: root
    password: hjk1679924491
#   session 失效时间（分钟）
  session:
    timeout: 86400
    store-type: redis
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  jackson:
    time-zone: Asia/Shanghai

  # redis 配置
  redis:
    port: 6379
    host: localhost
    database: 1
  activemq:
    broker-url:

#  redis:
#    port: 6379
#    host: 8.130.136.183
#    database: 1
#    password: 63KVTkg55tpjhoRvf2


  rabbitmq:
    host: 192.168.183.1
    port: 5672
    username: weslie
    password: 123321

  # 邮件配置
  mail:
    host: smtp.qq.com
    port: 587
    username: 169924491@qq.com
    password: jyljhbuvzxdeejcg


server:
  port: 8080
  servlet:
    context-path: /api
    session:
      cookie:
        domain: localhost
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
      logging:
        level:

avatar:
  upload:
    filePath: D:\avatar
#    filePath: /www/wwwroot/yujian-backend/avatar/