# 线上配置文件
# @author Treay
# 
# 注意开源时这个文件不要提交、或者不要填真实配置
spring:
  application:
    name: yujian-backend
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.130.136.183:3306/yujian?serverTimezone=Asia/Shanghai
    username: yujian
    password: wMXPRATjPCnaYApR
  # session 失效时间
  session:
    timeout: 86400
    store-type: redis
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  jackson:
    time-zone: Asia/Shanghai

  redis:
    port: 6379
    host: 8.130.136.183
    database: 1
    password: 63KVTkg55tpjhoRvf2
  activemq:
    broker-url:

  # rabbitmq 配置
  rabbitmq:
    host: 192.168.183.1
    port: 5672
    username: weslie
    password: 123321

  mail:
    host: smtp.qq.com
    port: 587
    username: 169924491@qq.com
    password: jyljhbuvzxdeejcg

server:
  port: 8090
  servlet:
    context-path: /api
    session:
      cookie:
        domain: localhost
  address: 0.0.0.0
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
avatar:
  upload:
    filePath: /www/wwwroot/yujian-backend/avatar/

